# Generated by Django 5.0.2 on 2024-03-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=10)),
                ("code", models.PositiveIntegerField()),
                ("info", models.CharField(max_length=1000)),
                ("ratings", models.JSONField(default=list)),
            ],
        ),
    ]
