# Generated by Django 5.0.2 on 2024-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
    ]
