# Generated by Django 5.0.2 on 2024-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_portal", "0002_course_average_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("course", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="ratings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
