# Generated by Django 5.0.2 on 2024-03-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review_portal", "0003_department_alter_course_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="course",
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="review_portal.department",
            ),
        ),
    ]
